{
  "hash": "02d002d26d94dac04598b76d2fa1a32a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Apéndice Costos Simulados\"\nsubtitle: \"Simulación de costos FastPGT vs Classic PGT\"\nnumber-sections: false\n\nlang: es\nbibliography: ONT-PGT.bib\ncsl: nature.csl\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n::: callout-note\n## Links\n\n**Presupuestos**: [Apéndice económico](appendix-costsRBKRAA.qmd)\n\n**Delivery 4**:  [Documento Principal](/index.html)\n:::\n\n---\n\n\n## 1. Simulación de costos FastPGT\n\nA continuación modelamos el uso completo de un kit Rapid Barcoding (RBK) con capacidad total de 144 muestras bajo un régimen operativo FAST.\n\nA diferencia de los modelos determinísticos previos, las corridas no se consideran independientes, sino que forman una secuencia acumulativa tal que:\n\n$$\n\\sum_{i=1}^{R} n_i = 144\n$$\n\ndonde $n_i$ representa el número de muestras procesadas en la corrida $i$, y $R$ es el número total de corridas necesarias para consumir el kit completo.\n\n\n\n### 1.1 Modelo de generación de corridas\n\nEl tamaño de cada corrida se modela como una variable aleatoria siguiendo una distribución normal truncada:\n\n$$\nn_i \\sim \\mathcal{N}(\\mu = 5.5,\\ \\sigma = 1.5), \\quad n_i \\in [4,10]\n$$\n\nEsta elección refleja un régimen clínico más realista que una distribución uniforme, donde:\n\n- la mayoría de las corridas se concentran en tamaños intermedios (5–6 muestras),\n- los valores extremos (corridas muy pequeñas o grandes) son menos frecuentes,\n- existe variabilidad inherente en la llegada de muestras.\n\nLa secuencia de corridas se genera iterativamente hasta alcanzar exactamente 144 muestras, ajustando la última corrida si es necesario para cumplir esta restricción.\n\n\n::: callout-note\n\nEl objetivo de esta simulación es:\n\n- estimar el costo promedio por muestra bajo condiciones realistas,\n- cuantificar la variabilidad del sistema,\n- identificar escenarios de mayor y menor eficiencia,\n- analizar el impacto de la fragmentación de corridas sobre el costo.\n\n - Este enfoque proporciona una representación más fiel del comportamiento operativo del sistema FastPGT en condiciones clínicas reales.\n\n - Se realizaron **300 simulaciones independientes**, cada una correspondiente a un ciclo completo de consumo de un kit RBK (144 barcodes), modelado como una secuencia de corridas hasta alcanzar dicha capacidad.\n\n::: \n\n\n### 1.2 Naturaleza estocástica del modelo\n\nDado que la generación de $n_i$ es aleatoria, cada simulación produce:\n\n- un número distinto de corridas $R$,\n- un número variable de flow cells utilizados,\n- una estructura diferente de eventos (lavados, cambios de FC, uso de RAA).\n\nPor lo tanto, el costo por muestra emerge como una variable aleatoria:\n\n$$\nC_{\\text{muestra}} \\sim f(\\{n_i\\})\n$$\n\ndonde $f$ representa la dinámica completa del sistema.\n\nEste enfoque permite capturar la variabilidad real del proceso y evaluar no solo el costo esperado, sino también su dispersión y escenarios extremos.\n\n\n\n----\n\n### Distribución de muestras por corrida (simulación)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\nLa distribución observada presenta una forma aproximadamente normal, centrada en 5–6 muestras por corrida, con límites entre 4 y 10.\n\nEsto refleja adecuadamente la variabilidad clínica esperada, donde:\n\n- la mayoría de las corridas son de tamaño pequeño,\n- los extremos (corridas muy pequeñas o grandes) son menos frecuentes.\n\nLa ligera distorsión en los valores bajos se debe al ajuste del último run para completar exactamente 144 muestras.\n\n----\n\n### Resumen de costos\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen estadístico del costo por muestra en FastPGT\n\n| Costo min (USD) | Costo medio (USD) | Desvío estándar |  P10  |  P90  | Costo max (USD) |\n|:---------------:|:-----------------:|:---------------:|:-----:|:-----:|:---------------:|\n|      72.23      |       83.4        |      3.25       | 84.04 | 84.71 |      84.93      |\n\n\n:::\n:::\n\n\nLa tabla muestra que:\n\n- El costo por muestra en el modelo FastPGT bajo condiciones realistas muestra un valor medio de aproximadamente **83.6 USD**, con una variabilidad moderada (desvío estándar de 3.08 USD). \n\n- La distribución se concentra en un rango relativamente estrecho, con valores entre 84 y 84.7 USD para los percentiles 10 y 90, lo que indica un comportamiento operativo bastante estable en la mayoría de los escenarios. \n\n- Se observan valores mínimos cercanos a 72.2 USD, correspondientes a configuraciones altamente eficientes, y máximos que alcanzan 96.7 USD en escenarios más fragmentados. \n\n- En conjunto, **estos resultados confirman que el costo por muestra no es fijo, sino que depende de la estructura de corridas y del aprovechamiento de los recursos del sistema**.\n\n\n----\n\n### Resumen de valores operativos\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen operativo del sistema (corridas y uso de flow cells)\n\n| Corridas (min) | Corridas (p90) | Corridas (max) | FC (min) | FC (p90) | FC (max) |\n|:--------------:|:--------------:|:--------------:|:--------:|:--------:|:--------:|\n|       23       |       28       |       29       |    4     |    5     |    5     |\n\n\n:::\n:::\n\n\nLa tabla muestra que:\n\n- Desde el punto de vista operativo, el sistema requiere un mínimo de 23 corridas para consumir completamente un kit RBK, pudiendo alcanzar hasta 31 en escenarios más fragmentados, con un percentil 90 en torno a 28 corridas. \n\n- Esta variabilidad se traduce directamente en el uso de flow cells, con un mínimo de 4 y un máximo de 6, siendo 5 el valor más frecuente en condiciones típicas. \n\n- Estos resultados reflejan la **naturaleza discreta del sistema**, donde pequeñas variaciones en el tamaño de las corridas impactan significativamente en el número total de ciclos necesarios y, en consecuencia, en la eficiencia global del proceso.\n\n----\n\n### Distribución del costo por muestra\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\nLa distribución del costo presenta dos características relevantes:\n\n1. **Un pico principal (~83–84 USD)**  \n   Representa el régimen operativo típico bajo condiciones realistas.\n\n2. **Un pico secundario a menor costo (~70–72 USD)**  \n   Corresponde a escenarios excepcionalmente eficientes, en los que:\n\n   - el número total de corridas es menor,\n   - el número de flow cells utilizados se reduce,\n   - la fragmentación de muestras es menor,\n   - el aprovechamiento de recursos es más cercano al óptimo.\n\nEste comportamiento multimodal surge de la naturaleza discreta del sistema, en particular:\n\n- el reemplazo de flow cells cada 6 corridas,\n- el uso condicionado de reactivos (RAA, wash),\n- la estructura secuencial de las corridas.\n\n---\n\n::: callout-note\n\n### Interpretación global\n\nLos resultados muestran que el costo por muestra no es un valor fijo, sino una variable emergente dependiente de la organización de las corridas.\n\nEn particular:\n\n- una mayor fragmentación (corridas pequeñas frecuentes) aumenta el costo,\n- una mejor agrupación de muestras reduce significativamente el costo,\n- existen escenarios de alta eficiencia, aunque no representan el comportamiento promedio.\n\nEsto confirma que el sistema FastPGT está gobernado por dinámicas operativas discretas, más que por una relación lineal entre insumos y muestras procesadas.\n\n\n\n### Implicancias operativas\n\nEste análisis permite:\n\n- cuantificar el impacto económico de la variabilidad clínica,\n- identificar condiciones de operación eficientes,\n- fundamentar estrategias de optimización, como:\n  - establecimiento de tamaños mínimos de corrida,\n  - agrupamiento parcial de muestras,\n  - planificación del uso de flow cells.\n\nEn conjunto, el modelo proporciona una herramienta robusta para la toma de decisiones operativas y económicas en entornos de PGT rápido.\n\n:::\n\n---\n\n## 2. Simulación bajo régimen intermedio\n\n\nModificando el escenario anterior, definimos:\n\n\n\n$$\nn_i \\sim \\mathcal{N}(\\mu = 16,\\ \\sigma = 2), \\quad n_i \\in [11,22]\n$$\ndonde:\n \n$n_i$ es el número de muestras por corrida, que siguen una distribución normal truncada $(N)$ con extremos entre 11 y 22, de media: $\\mu$ y distribución standard: $\\sigma$,\n\nEste modelo refleja condiciones operativas donde las muestras se agrupan antes de ser procesadas, optimizando el uso de recursos.\n\n\n\n::: {.cell}\n\n:::\n\n\n### Tabla de Costos\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen de costos bajo régimen intermedio\n\n| Costo medio (USD) | Desvío estándar | P10  | Mediana (P50) | P90  |\n|:-----------------:|:---------------:|:----:|:-------------:|:----:|\n|       61.6        |      0.99       | 61.5 |     61.5      | 61.8 |\n\n\n:::\n:::\n\n\n\n### Tabla de Operación\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen operativo bajo régimen intermedio\n\n| Corridas (min) | Corridas (mediana) | Corridas (p90) | Corridas (max) | FC (min) | FC (mediana) | FC (p90) | FC (max) |\n|:--------------:|:------------------:|:--------------:|:--------------:|:--------:|:------------:|:--------:|:--------:|\n|       9        |         9          |       10       |       11       |    3     |      4       |    4     |    5     |\n\n\n:::\n:::\n\n\n### Distribución de muestras por corrida (PGT intermedio)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n### Gráfico de Costos\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n\n----\n\n## 3. Simulación bajo régimen PGT clásico / batch\n\n\nEn este escenario, el tamaño de corrida es fijo y determinístico, por lo que no se modela como una variable aleatoria. En consecuencia, la variabilidad del sistema desaparece y el costo por muestra converge a un valor único.\n\ndonde:\n\n$$\n\\sum_{i=1}^{R} n_i = 144, \\quad n_i = 24 \\ \\forall i\n$$\nSiendo el valor $R$:\n\n$$\nR = \\frac{144}{24} = 6\n$$\nEn este régimen, el sistema deja de ser estocástico y pasa a ser completamente determinístico. La estructura de corridas está completamente definida a priori, eliminando la variabilidad observada en los escenarios FAST e intermedio.\n\nEste modelo refleja condiciones operativas donde las muestras se guardan hasta completar un batch de corrida, exactamente como se hace en los escenarios clásicos de PGT-A.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n### Tabla de Costos\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen de costos bajo régimen batch (PGT estándar)\n\n| Costo medio (USD) | Desvío estándar | P10  | Mediana (P50) | P90  |\n|:-----------------:|:---------------:|:----:|:-------------:|:----:|\n|       49.5        |        0        | 49.5 |     49.5      | 49.5 |\n\n\n:::\n:::\n\n\n\n### Tabla de Operación\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Resumen operativo bajo régimen batch\n\n| Corridas (min) | Corridas (mediana) | Corridas (p90) | Corridas (max) | FC (min) | FC (mediana) | FC (p90) | FC (max) |\n|:--------------:|:------------------:|:--------------:|:--------------:|:--------:|:------------:|:--------:|:--------:|\n|       6        |         6          |       6        |       6        |    3     |      3       |    3     |    3     |\n\n\n:::\n:::\n\n\n### Distribución de muestras por corrida (PGT estándar)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Gráfico de Costos\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n### Interpretación del régimen PGT clásico o batch\n\nEl régimen batch presenta la reducción máxima de la variabilidad del sistema, con el menor número de corridas necesarias para consumir un kit RBK.\n\nLa distribución del costo en el régimen batch no presenta varianza baja, lo que hace que la estimación de densidad resulte poco informativa. Por este motivo, se utilizan representaciones basadas en histogramas, que reflejan mejor la concentración de valores.\n\nEl aumento en el tamaño promedio de corrida reduce la fragmentación del proceso, lo que se traduce en una mayor eficiencia económica y una disminución del costo por muestra.\n\n::: callout-note\n\n## Comparación de los costos por muestra: FAST vs Intermedio vs PGT clásico / batch\n\n- En comparación con el régimen FAST, el escenario intermedio y batch representan un comportamiento más estable y predecible, con una la reducción de costos importantes, y curiosamnete, no tan diferentes, lo cual genera una ventaja operacional importante: **No hay mucha diferencia entre los costos BATCH vs INTERMEDIO** lo cual relaja la decisión del laboratorio sobre qué procedimiento y cuanto tiempo deben esperar las muestras.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](appendix-simulations_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n----\n## 4. Tabla de simulaciones\n\n### 4.1. FastPGT\n\nThe full simulation output contains 23 variables capturing operational and economic states. \nFor clarity, a reduced subset of key variables is presented here.\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Resumen de simulación</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Run </th>\n   <th style=\"text-align:left;\"> Samples </th>\n   <th style=\"text-align:left;\"> Total Samples </th>\n   <th style=\"text-align:left;\"> RBK # </th>\n   <th style=\"text-align:left;\"> RBK Cycle </th>\n   <th style=\"text-align:left;\"> RAA Cycle </th>\n   <th style=\"text-align:left;\"> Flow Cell # </th>\n   <th style=\"text-align:left;\"> Event </th>\n   <th style=\"text-align:left;\"> Run Cost (USD) </th>\n   <th style=\"text-align:left;\"> Cumulative Cost (USD) </th>\n   <th style=\"text-align:left;\"> Avg Cost / Sample (USD) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 8.00 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Arranca_RBK </td>\n   <td style=\"text-align:left;\"> 410.92 </td>\n   <td style=\"text-align:left;\"> 2,968.00 </td>\n   <td style=\"text-align:left;\"> 371.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 237.79 </td>\n   <td style=\"text-align:left;\"> 3,000.33 </td>\n   <td style=\"text-align:left;\"> 250.03 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 237.79 </td>\n   <td style=\"text-align:left;\"> 3,032.67 </td>\n   <td style=\"text-align:left;\"> 189.54 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 340.52 </td>\n   <td style=\"text-align:left;\"> 3,065.00 </td>\n   <td style=\"text-align:left;\"> 139.32 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 28 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 340.52 </td>\n   <td style=\"text-align:left;\"> 3,097.33 </td>\n   <td style=\"text-align:left;\"> 110.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 33 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 289.16 </td>\n   <td style=\"text-align:left;\"> 3,129.67 </td>\n   <td style=\"text-align:left;\"> 94.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:left;\"> 7.00 </td>\n   <td style=\"text-align:left;\"> 40 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra RAA </td>\n   <td style=\"text-align:left;\"> 450.06 </td>\n   <td style=\"text-align:left;\"> 4,797.67 </td>\n   <td style=\"text-align:left;\"> 119.94 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 46 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 431.02 </td>\n   <td style=\"text-align:left;\"> 4,830.00 </td>\n   <td style=\"text-align:left;\"> 105.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 50 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 328.29 </td>\n   <td style=\"text-align:left;\"> 4,862.33 </td>\n   <td style=\"text-align:left;\"> 97.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 56 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 431.02 </td>\n   <td style=\"text-align:left;\"> 4,894.67 </td>\n   <td style=\"text-align:left;\"> 87.40 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 61 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 4,927.00 </td>\n   <td style=\"text-align:left;\"> 80.77 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 66 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 4,959.33 </td>\n   <td style=\"text-align:left;\"> 75.14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 13 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 71 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 13 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra RAA </td>\n   <td style=\"text-align:left;\"> 347.33 </td>\n   <td style=\"text-align:left;\"> 6,627.33 </td>\n   <td style=\"text-align:left;\"> 93.34 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 76 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 6,659.67 </td>\n   <td style=\"text-align:left;\"> 87.63 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 82 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 431.02 </td>\n   <td style=\"text-align:left;\"> 6,692.00 </td>\n   <td style=\"text-align:left;\"> 81.61 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 87 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 6,724.33 </td>\n   <td style=\"text-align:left;\"> 77.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 91 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 328.29 </td>\n   <td style=\"text-align:left;\"> 6,756.67 </td>\n   <td style=\"text-align:left;\"> 74.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 96 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 6,789.00 </td>\n   <td style=\"text-align:left;\"> 70.72 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 101 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra WGA + Compra RAA </td>\n   <td style=\"text-align:left;\"> 347.33 </td>\n   <td style=\"text-align:left;\"> 10,271.40 </td>\n   <td style=\"text-align:left;\"> 101.70 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 107 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 431.02 </td>\n   <td style=\"text-align:left;\"> 10,303.73 </td>\n   <td style=\"text-align:left;\"> 96.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 21 </td>\n   <td style=\"text-align:left;\"> 9.00 </td>\n   <td style=\"text-align:left;\"> 116 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 21 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 585.12 </td>\n   <td style=\"text-align:left;\"> 10,336.07 </td>\n   <td style=\"text-align:left;\"> 89.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 121 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 10,368.40 </td>\n   <td style=\"text-align:left;\"> 85.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 23 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 125 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 23 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 328.29 </td>\n   <td style=\"text-align:left;\"> 10,400.73 </td>\n   <td style=\"text-align:left;\"> 83.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 5.00 </td>\n   <td style=\"text-align:left;\"> 130 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 379.66 </td>\n   <td style=\"text-align:left;\"> 10,433.07 </td>\n   <td style=\"text-align:left;\"> 80.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:left;\"> 6.00 </td>\n   <td style=\"text-align:left;\"> 136 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra RAA </td>\n   <td style=\"text-align:left;\"> 398.69 </td>\n   <td style=\"text-align:left;\"> 12,101.07 </td>\n   <td style=\"text-align:left;\"> 88.98 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 26 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 140 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 26 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 328.29 </td>\n   <td style=\"text-align:left;\"> 12,133.40 </td>\n   <td style=\"text-align:left;\"> 86.67 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 27 </td>\n   <td style=\"text-align:left;\"> 4.00 </td>\n   <td style=\"text-align:left;\"> 144 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 27 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 328.29 </td>\n   <td style=\"text-align:left;\"> 12,165.73 </td>\n   <td style=\"text-align:left;\"> 84.48 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 5.33 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 144 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 1 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 5 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> PROMEDIO </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 370.68 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 12,165.73 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 84.48 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.callout-note collapse=\"true\"}\n## Click to see the full simulation\n\nThis simulation output contains all operational state variables and is provided here for reproducibility.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5f88f8459908b178ff13\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5f88f8459908b178ff13\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],[8,4,4,6,6,5,7,6,4,6,5,5,5,5,6,5,4,5,5,6,9,5,4,5,6,4,4],[8,12,16,22,28,33,40,46,50,56,61,66,71,76,82,87,91,96,101,107,116,121,125,130,136,140,144],[8,12,16,22,28,33,7,13,17,23,28,33,5,10,16,21,25,30,5,11,20,25,29,34,6,10,14],[1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,5,5,5],[\"Arranca_RBK\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Nuevo FC + Compra RAA\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Nuevo FC + Compra RAA\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Nuevo FC + Compra WGA + Compra RAA\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Wash\",\"Nuevo FC + Compra RAA\",\"Wash\",\"Wash\"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],[0,0,0,0,0,0,1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5,6,1,2,3],[0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4],[151.2,75.59999999999999,75.59999999999999,113.4,113.4,94.5,132.3,113.4,75.59999999999999,113.4,94.5,94.5,94.5,94.5,113.4,94.5,75.59999999999999,94.5,94.5,113.4,170.1,94.5,75.59999999999999,94.5,113.4,75.59999999999999,75.59999999999999],[187.5,93.75,93.75,140.625,140.625,117.1875,164.0625,140.625,93.75,140.625,117.1875,117.1875,117.1875,117.1875,140.625,117.1875,93.75,117.1875,117.1875,140.625,210.9375,117.1875,93.75,117.1875,140.625,93.75,93.75],[0,0,0,0,0,0,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5,90.5],[72.22222222222223,36.11111111111111,36.11111111111111,54.16666666666667,54.16666666666667,45.13888888888889,63.19444444444445,54.16666666666667,36.11111111111111,54.16666666666667,45.13888888888889,45.13888888888889,45.13888888888889,45.13888888888889,54.16666666666667,45.13888888888889,36.11111111111111,45.13888888888889,45.13888888888889,54.16666666666667,81.25,45.13888888888889,36.11111111111111,45.13888888888889,54.16666666666667,36.11111111111111,36.11111111111111],[0,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334],[18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9],[23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375],[0,0,0,0,0,0,12.92857142857143,15.08333333333333,22.625,15.08333333333333,18.1,18.1,18.1,18.1,15.08333333333333,18.1,22.625,18.1,18.1,15.08333333333333,10.05555555555556,18.1,22.625,18.1,15.08333333333333,22.625,22.625],[9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779],[0,8.083333333333334,8.083333333333334,5.388888888888889,5.388888888888889,6.466666666666667,0,5.388888888888889,8.083333333333334,5.388888888888889,6.466666666666667,6.466666666666667,0,6.466666666666667,5.388888888888889,6.466666666666667,8.083333333333334,6.466666666666667,0,5.388888888888889,3.592592592592593,6.466666666666667,8.083333333333334,6.466666666666667,0,8.083333333333334,8.083333333333334],[410.9222222222222,237.7944444444445,237.7944444444445,340.525,340.525,289.1597222222222,450.0569444444444,431.025,328.2944444444444,431.025,379.6597222222222,379.6597222222222,347.3263888888889,379.6597222222222,431.025,379.6597222222222,328.2944444444444,379.6597222222222,347.3263888888889,431.025,585.1208333333334,379.6597222222222,328.2944444444444,379.6597222222222,398.6916666666667,328.2944444444444,328.2944444444444],[2968,3000.333333333333,3032.666666666667,3065,3097.333333333334,3129.666666666667,4797.666666666668,4830.000000000001,4862.333333333334,4894.666666666667,4927,4959.333333333333,6627.333333333333,6659.666666666666,6691.999999999999,6724.333333333332,6756.666666666665,6788.999999999998,10271.4,10303.73333333333,10336.06666666667,10368.4,10400.73333333333,10433.06666666667,12101.06666666667,12133.4,12165.73333333334],[371,250.0277777777778,189.5416666666667,139.3181818181818,110.6190476190476,94.83838383838386,119.9416666666667,105,97.24666666666668,87.40476190476191,80.77049180327869,75.14141414141413,93.34272300469483,87.62719298245614,81.60975609756096,77.29118773946358,74.24908424908423,70.71874999999999,101.6970297029703,96.29657320872273,89.10402298850573,85.68925619834711,83.20586666666667,80.25435897435898,88.97843137254903,86.66714285714286,84.48425925925928]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>corrida<\\/th>\\n      <th>muestras<\\/th>\\n      <th>muestras_totales<\\/th>\\n      <th>muestras_en_FC<\\/th>\\n      <th>FC_actual<\\/th>\\n      <th>evento<\\/th>\\n      <th>RBK_id<\\/th>\\n      <th>run_in_rbk_counter<\\/th>\\n      <th>raa_counter<\\/th>\\n      <th>raa_cycle_global<\\/th>\\n      <th>costo_WGA<\\/th>\\n      <th>costo_FC<\\/th>\\n      <th>costo_RAA<\\/th>\\n      <th>costo_RBK<\\/th>\\n      <th>costo_wash<\\/th>\\n      <th>costo_WGA_unit<\\/th>\\n      <th>costo_FC_unit<\\/th>\\n      <th>costo_RAA_unit<\\/th>\\n      <th>costo_RBK_unit<\\/th>\\n      <th>costo_wash_unit<\\/th>\\n      <th>costo_run_modelado<\\/th>\\n      <th>costo_acumulado<\\/th>\\n      <th>costo_promedio_global<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"scrollX\":true,\"columnDefs\":[{\"targets\":10,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":11,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":12,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":13,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":14,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":15,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":16,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":17,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":18,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":19,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":20,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":21,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":22,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":0,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":8,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":9,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]},{\"name\":\"corrida\",\"targets\":0},{\"name\":\"muestras\",\"targets\":1},{\"name\":\"muestras_totales\",\"targets\":2},{\"name\":\"muestras_en_FC\",\"targets\":3},{\"name\":\"FC_actual\",\"targets\":4},{\"name\":\"evento\",\"targets\":5},{\"name\":\"RBK_id\",\"targets\":6},{\"name\":\"run_in_rbk_counter\",\"targets\":7},{\"name\":\"raa_counter\",\"targets\":8},{\"name\":\"raa_cycle_global\",\"targets\":9},{\"name\":\"costo_WGA\",\"targets\":10},{\"name\":\"costo_FC\",\"targets\":11},{\"name\":\"costo_RAA\",\"targets\":12},{\"name\":\"costo_RBK\",\"targets\":13},{\"name\":\"costo_wash\",\"targets\":14},{\"name\":\"costo_WGA_unit\",\"targets\":15},{\"name\":\"costo_FC_unit\",\"targets\":16},{\"name\":\"costo_RAA_unit\",\"targets\":17},{\"name\":\"costo_RBK_unit\",\"targets\":18},{\"name\":\"costo_wash_unit\",\"targets\":19},{\"name\":\"costo_run_modelado\",\"targets\":20},{\"name\":\"costo_acumulado\",\"targets\":21},{\"name\":\"costo_promedio_global\",\"targets\":22}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\",\"options.columnDefs.6.render\",\"options.columnDefs.7.render\",\"options.columnDefs.8.render\",\"options.columnDefs.9.render\",\"options.columnDefs.10.render\",\"options.columnDefs.11.render\",\"options.columnDefs.12.render\",\"options.columnDefs.13.render\",\"options.columnDefs.14.render\",\"options.columnDefs.15.render\",\"options.columnDefs.16.render\",\"options.columnDefs.17.render\",\"options.columnDefs.18.render\",\"options.columnDefs.19.render\",\"options.columnDefs.20.render\",\"options.columnDefs.21.render\",\"options.columnDefs.22.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n\n\n\n\n\n### 4.2. PGT Intermedio\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Resumen de simulación (Intermedio)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Run </th>\n   <th style=\"text-align:left;\"> Samples </th>\n   <th style=\"text-align:left;\"> Total Samples </th>\n   <th style=\"text-align:left;\"> RBK # </th>\n   <th style=\"text-align:left;\"> RBK Cycle </th>\n   <th style=\"text-align:left;\"> RAA Cycle </th>\n   <th style=\"text-align:left;\"> Flow Cell # </th>\n   <th style=\"text-align:left;\"> Event </th>\n   <th style=\"text-align:left;\"> Run Cost (USD) </th>\n   <th style=\"text-align:left;\"> Cumulative Cost (USD) </th>\n   <th style=\"text-align:left;\"> Avg Cost / Sample (USD) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 15.0 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Arranca_RBK </td>\n   <td style=\"text-align:left;\"> 770.48 </td>\n   <td style=\"text-align:left;\"> 2,968.00 </td>\n   <td style=\"text-align:left;\"> 197.87 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 17.0 </td>\n   <td style=\"text-align:left;\"> 32 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 905.54 </td>\n   <td style=\"text-align:left;\"> 3,000.33 </td>\n   <td style=\"text-align:left;\"> 93.76 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 14.0 </td>\n   <td style=\"text-align:left;\"> 46 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 751.45 </td>\n   <td style=\"text-align:left;\"> 3,032.67 </td>\n   <td style=\"text-align:left;\"> 65.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 18.0 </td>\n   <td style=\"text-align:left;\"> 64 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Nuevo FC </td>\n   <td style=\"text-align:left;\"> 924.58 </td>\n   <td style=\"text-align:left;\"> 4,157.67 </td>\n   <td style=\"text-align:left;\"> 64.96 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 13.0 </td>\n   <td style=\"text-align:left;\"> 77 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 700.08 </td>\n   <td style=\"text-align:left;\"> 4,190.00 </td>\n   <td style=\"text-align:left;\"> 54.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 16.0 </td>\n   <td style=\"text-align:left;\"> 93 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 854.18 </td>\n   <td style=\"text-align:left;\"> 4,222.33 </td>\n   <td style=\"text-align:left;\"> 45.40 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:left;\"> 16.0 </td>\n   <td style=\"text-align:left;\"> 109 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra WGA + Compra RAA </td>\n   <td style=\"text-align:left;\"> 912.34 </td>\n   <td style=\"text-align:left;\"> 7,704.73 </td>\n   <td style=\"text-align:left;\"> 70.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 16.0 </td>\n   <td style=\"text-align:left;\"> 125 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 944.68 </td>\n   <td style=\"text-align:left;\"> 7,737.07 </td>\n   <td style=\"text-align:left;\"> 61.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:left;\"> 16.0 </td>\n   <td style=\"text-align:left;\"> 141 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 944.68 </td>\n   <td style=\"text-align:left;\"> 7,769.40 </td>\n   <td style=\"text-align:left;\"> 55.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:left;\"> 3.0 </td>\n   <td style=\"text-align:left;\"> 144 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> Nuevo FC </td>\n   <td style=\"text-align:left;\"> 244.60 </td>\n   <td style=\"text-align:left;\"> 8,894.40 </td>\n   <td style=\"text-align:left;\"> 61.77 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 14.4 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 144 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 1 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 4 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> PROMEDIO </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 795.26 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 8,894.40 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 61.77 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.callout-note collapse=\"true\"}\n## Click to see the full simulation\n\nThis simulation output contains all operational state variables and is provided here for reproducibility.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-31c703d4d2d314dd4894\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-31c703d4d2d314dd4894\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[1,2,3,4,5,6,7,8,9,10],[15,17,14,18,13,16,16,16,16,3],[15,32,46,64,77,93,109,125,141,144],[15,32,46,18,31,47,16,32,48,3],[1,1,1,2,2,2,3,3,3,4],[\"Arranca_RBK\",\"Wash\",\"Wash\",\"Nuevo FC\",\"Wash\",\"Wash\",\"Nuevo FC + Compra WGA + Compra RAA\",\"Wash\",\"Wash\",\"Nuevo FC\"],[1,1,1,1,1,1,1,1,1,1],[1,2,3,4,5,6,7,8,9,10],[0,0,0,0,0,0,1,2,3,4],[0,0,0,0,0,0,1,1,1,1],[283.5,321.3,264.6,340.2,245.7,302.4,302.4,302.4,302.4,56.7],[351.5625,398.4375,328.125,421.875,304.6875,375,375,375,375,70.3125],[0,0,0,0,0,0,90.5,90.5,90.5,90.5],[135.4166666666667,153.4722222222222,126.3888888888889,162.5,117.3611111111111,144.4444444444445,144.4444444444445,144.4444444444445,144.4444444444445,27.08333333333334],[0,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334,0,32.33333333333334,32.33333333333334,0],[18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9,18.9],[23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375,23.4375],[0,0,0,0,0,0,5.65625,5.65625,5.65625,30.16666666666667],[9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779],[0,1.901960784313726,2.30952380952381,0,2.487179487179487,2.020833333333333,0,2.020833333333333,2.020833333333333,0],[770.4791666666667,905.5430555555555,751.4472222222222,924.575,700.0819444444445,854.1777777777778,912.3444444444444,944.6777777777778,944.6777777777778,244.5958333333333],[2968,3000.333333333333,3032.666666666667,4157.666666666667,4190,4222.333333333333,7704.733333333333,7737.066666666666,7769.399999999999,8894.399999999998],[197.8666666666667,93.76041666666667,65.92753623188406,64.96354166666667,54.41558441558441,45.40143369175627,70.68562691131498,61.89653333333332,55.10212765957446,61.76666666666665]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>corrida<\\/th>\\n      <th>muestras<\\/th>\\n      <th>muestras_totales<\\/th>\\n      <th>muestras_en_FC<\\/th>\\n      <th>FC_actual<\\/th>\\n      <th>evento<\\/th>\\n      <th>RBK_id<\\/th>\\n      <th>run_in_rbk_counter<\\/th>\\n      <th>raa_counter<\\/th>\\n      <th>raa_cycle_global<\\/th>\\n      <th>costo_WGA<\\/th>\\n      <th>costo_FC<\\/th>\\n      <th>costo_RAA<\\/th>\\n      <th>costo_RBK<\\/th>\\n      <th>costo_wash<\\/th>\\n      <th>costo_WGA_unit<\\/th>\\n      <th>costo_FC_unit<\\/th>\\n      <th>costo_RAA_unit<\\/th>\\n      <th>costo_RBK_unit<\\/th>\\n      <th>costo_wash_unit<\\/th>\\n      <th>costo_run_modelado<\\/th>\\n      <th>costo_acumulado<\\/th>\\n      <th>costo_promedio_global<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"scrollX\":true,\"columnDefs\":[{\"targets\":10,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":11,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":12,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":13,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":14,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":15,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":16,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":17,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":18,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":19,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":20,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":21,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":22,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":0,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":8,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":9,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]},{\"name\":\"corrida\",\"targets\":0},{\"name\":\"muestras\",\"targets\":1},{\"name\":\"muestras_totales\",\"targets\":2},{\"name\":\"muestras_en_FC\",\"targets\":3},{\"name\":\"FC_actual\",\"targets\":4},{\"name\":\"evento\",\"targets\":5},{\"name\":\"RBK_id\",\"targets\":6},{\"name\":\"run_in_rbk_counter\",\"targets\":7},{\"name\":\"raa_counter\",\"targets\":8},{\"name\":\"raa_cycle_global\",\"targets\":9},{\"name\":\"costo_WGA\",\"targets\":10},{\"name\":\"costo_FC\",\"targets\":11},{\"name\":\"costo_RAA\",\"targets\":12},{\"name\":\"costo_RBK\",\"targets\":13},{\"name\":\"costo_wash\",\"targets\":14},{\"name\":\"costo_WGA_unit\",\"targets\":15},{\"name\":\"costo_FC_unit\",\"targets\":16},{\"name\":\"costo_RAA_unit\",\"targets\":17},{\"name\":\"costo_RBK_unit\",\"targets\":18},{\"name\":\"costo_wash_unit\",\"targets\":19},{\"name\":\"costo_run_modelado\",\"targets\":20},{\"name\":\"costo_acumulado\",\"targets\":21},{\"name\":\"costo_promedio_global\",\"targets\":22}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\",\"options.columnDefs.6.render\",\"options.columnDefs.7.render\",\"options.columnDefs.8.render\",\"options.columnDefs.9.render\",\"options.columnDefs.10.render\",\"options.columnDefs.11.render\",\"options.columnDefs.12.render\",\"options.columnDefs.13.render\",\"options.columnDefs.14.render\",\"options.columnDefs.15.render\",\"options.columnDefs.16.render\",\"options.columnDefs.17.render\",\"options.columnDefs.18.render\",\"options.columnDefs.19.render\",\"options.columnDefs.20.render\",\"options.columnDefs.21.render\",\"options.columnDefs.22.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n\n\n\n### 4.3. PGT Clásico o batch\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Resumen de simulación (Batch)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Run </th>\n   <th style=\"text-align:left;\"> Samples </th>\n   <th style=\"text-align:left;\"> Total Samples </th>\n   <th style=\"text-align:left;\"> RBK # </th>\n   <th style=\"text-align:left;\"> RBK Cycle </th>\n   <th style=\"text-align:left;\"> RAA Cycle </th>\n   <th style=\"text-align:left;\"> Flow Cell # </th>\n   <th style=\"text-align:left;\"> Event </th>\n   <th style=\"text-align:left;\"> Run Cost (USD) </th>\n   <th style=\"text-align:left;\"> Cumulative Cost (USD) </th>\n   <th style=\"text-align:left;\"> Avg Cost / Sample (USD) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Arranca_RBK </td>\n   <td style=\"text-align:left;\"> 1,232.77 </td>\n   <td style=\"text-align:left;\"> 2,968.00 </td>\n   <td style=\"text-align:left;\"> 123.67 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 48 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 1,265.10 </td>\n   <td style=\"text-align:left;\"> 3,000.33 </td>\n   <td style=\"text-align:left;\"> 62.51 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 72 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Nuevo FC </td>\n   <td style=\"text-align:left;\"> 1,232.77 </td>\n   <td style=\"text-align:left;\"> 4,125.33 </td>\n   <td style=\"text-align:left;\"> 57.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 96 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 1,265.10 </td>\n   <td style=\"text-align:left;\"> 4,157.67 </td>\n   <td style=\"text-align:left;\"> 43.31 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 120 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Nuevo FC + Compra WGA </td>\n   <td style=\"text-align:left;\"> 1,232.77 </td>\n   <td style=\"text-align:left;\"> 7,097.07 </td>\n   <td style=\"text-align:left;\"> 59.14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:left;\"> 144 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:left;\"> 0 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:left;\"> Wash </td>\n   <td style=\"text-align:left;\"> 1,265.10 </td>\n   <td style=\"text-align:left;\"> 7,129.40 </td>\n   <td style=\"text-align:left;\"> 49.51 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 24 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 144 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 1 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> NA </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 3 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> PROMEDIO </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 1,248.93 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 7,129.40 </td>\n   <td style=\"text-align:left;font-weight: bold;background-color: rgba(239, 239, 239, 255) !important;\"> 49.51 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n::: {.callout-note collapse=\"true\"}\n\n## Click to see the full simulation (Batch)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-ff230a601afa7553c1fc\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ff230a601afa7553c1fc\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[1,2,3,4,5,6],[24,24,24,24,24,24],[24,48,72,96,120,144],[24,48,24,48,24,48],[1,1,2,2,3,3],[\"Arranca_RBK\",\"Wash\",\"Nuevo FC\",\"Wash\",\"Nuevo FC + Compra WGA\",\"Wash\"],[1,1,1,1,1,1],[1,2,3,4,5,6],[0,0,0,0,0,0],[0,0,0,0,0,0],[453.6,453.6,453.6,453.6,453.6,453.6],[562.5,562.5,562.5,562.5,562.5,562.5],[0,0,0,0,0,0],[216.6666666666667,216.6666666666667,216.6666666666667,216.6666666666667,216.6666666666667,216.6666666666667],[0,32.33333333333334,0,32.33333333333334,0,32.33333333333334],[18.9,18.9,18.9,18.9,18.9,18.9],[23.4375,23.4375,23.4375,23.4375,23.4375,23.4375],[0,0,0,0,0,0],[9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779,9.027777777777779],[0,1.347222222222222,0,1.347222222222222,0,1.347222222222222],[1232.766666666667,1265.1,1232.766666666667,1265.1,1232.766666666667,1265.1],[2968,3000.333333333333,4125.333333333334,4157.666666666667,7097.066666666667,7129.4],[123.6666666666667,62.50694444444445,57.2962962962963,43.30902777777778,59.14222222222222,49.50972222222222]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>corrida<\\/th>\\n      <th>muestras<\\/th>\\n      <th>muestras_totales<\\/th>\\n      <th>muestras_en_FC<\\/th>\\n      <th>FC_actual<\\/th>\\n      <th>evento<\\/th>\\n      <th>RBK_id<\\/th>\\n      <th>run_in_rbk_counter<\\/th>\\n      <th>raa_counter<\\/th>\\n      <th>raa_cycle_global<\\/th>\\n      <th>costo_WGA<\\/th>\\n      <th>costo_FC<\\/th>\\n      <th>costo_RAA<\\/th>\\n      <th>costo_RBK<\\/th>\\n      <th>costo_wash<\\/th>\\n      <th>costo_WGA_unit<\\/th>\\n      <th>costo_FC_unit<\\/th>\\n      <th>costo_RAA_unit<\\/th>\\n      <th>costo_RBK_unit<\\/th>\\n      <th>costo_wash_unit<\\/th>\\n      <th>costo_run_modelado<\\/th>\\n      <th>costo_acumulado<\\/th>\\n      <th>costo_promedio_global<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":15,\"scrollX\":true,\"columnDefs\":[{\"targets\":10,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":11,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":12,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":13,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":14,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":15,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":16,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":17,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":18,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":19,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":20,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":21,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":22,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":0,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":7,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":8,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":9,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 0, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]},{\"name\":\"corrida\",\"targets\":0},{\"name\":\"muestras\",\"targets\":1},{\"name\":\"muestras_totales\",\"targets\":2},{\"name\":\"muestras_en_FC\",\"targets\":3},{\"name\":\"FC_actual\",\"targets\":4},{\"name\":\"evento\",\"targets\":5},{\"name\":\"RBK_id\",\"targets\":6},{\"name\":\"run_in_rbk_counter\",\"targets\":7},{\"name\":\"raa_counter\",\"targets\":8},{\"name\":\"raa_cycle_global\",\"targets\":9},{\"name\":\"costo_WGA\",\"targets\":10},{\"name\":\"costo_FC\",\"targets\":11},{\"name\":\"costo_RAA\",\"targets\":12},{\"name\":\"costo_RBK\",\"targets\":13},{\"name\":\"costo_wash\",\"targets\":14},{\"name\":\"costo_WGA_unit\",\"targets\":15},{\"name\":\"costo_FC_unit\",\"targets\":16},{\"name\":\"costo_RAA_unit\",\"targets\":17},{\"name\":\"costo_RBK_unit\",\"targets\":18},{\"name\":\"costo_wash_unit\",\"targets\":19},{\"name\":\"costo_run_modelado\",\"targets\":20},{\"name\":\"costo_acumulado\",\"targets\":21},{\"name\":\"costo_promedio_global\",\"targets\":22}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,15,25,50,100]}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\",\"options.columnDefs.6.render\",\"options.columnDefs.7.render\",\"options.columnDefs.8.render\",\"options.columnDefs.9.render\",\"options.columnDefs.10.render\",\"options.columnDefs.11.render\",\"options.columnDefs.12.render\",\"options.columnDefs.13.render\",\"options.columnDefs.14.render\",\"options.columnDefs.15.render\",\"options.columnDefs.16.render\",\"options.columnDefs.17.render\",\"options.columnDefs.18.render\",\"options.columnDefs.19.render\",\"options.columnDefs.20.render\",\"options.columnDefs.21.render\",\"options.columnDefs.22.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n:::\n\n::: callout-important\n\n## 5. Conclusiones\n\nLas simulaciones de costos muestran valores competitivos para cualquiera de los 3 escenarios ensayados. No obstante, **queda revisar si la amplificación WGA con phy29 funciona como pensamos, si los rendimientos de FC, RAA y RBK son exactamente los considerados en los supuestos y si los tiempos de los diferentes ensayos son compatibles para cada uno de los escenarios**.\n\nEstos supuestos podrán verificarse o modificarse luego de los ensyaos experimentales realizados por Pufo. \n\n:::\n\n",
    "supporting": [
      "appendix-simulations_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}