project:
  type: website
  render:
      - index.qmd
      - appendix-technical.qmd
      - appendix-experimental.qmd
      - appendix-costsRBKRAA.qmd
      - appendix-simulations.qmd
      - appendix-clinico.qmd
      - appendix-inversion.qmd
      - appendix-modelo.qmd

 

website:
  title: "FastPGT"
  sidebar:
    contents:
      - index.qmd
      - appendix-technical.qmd
      - appendix-experimental.qmd
      - appendix-costsRBKRAA.qmd 
      - appendix-simulations.qmd
      - appendix-clinico.qmd
      - appendix-inversion.qmd
      - appendix-modelo.qmd


format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: styles.css