project:
  type: website
  render:
    - index.qmd
    - appendix-technical.qmd
    - appendix-clinico.qmd
    - appendix-experimental/fase1-havanna.qmd
    - appendix-experimental/fase2-rbk.qmd
    - appendix-economico/costsRBKRAA.qmd
    - appendix-economico/simulations.qmd
    - appendix-economico/inversion.qmd
    - appendix-modelo.qmd

website:
  sidebar:
    collapse-level: 1
    contents:
      - file: index.qmd
        text: "FastPGT"

      - file: appendix-technical.qmd
        text: "Apéndice Técnico"

      - file: appendix-clinico.qmd
        text: "Apéndice Clínico-Embriológico"

      - section: "Apéndice Experimental"
        contents:
          - file: appendix-experimental/fase1-havanna.qmd
          - file: appendix-experimental/fase2-rbk.qmd

      - section: "Apéndice Económico"
        contents:
          - file: appendix-economico/costsRBKRAA.qmd
          - file: appendix-economico/simulations.qmd
          - file: appendix-economico/inversion.qmd

      - file: appendix-modelo.qmd

    # 👇 CLAVE
    search: true

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: styles.css