project:
  type: website
  render:
    - index.qmd
    - appendix-technical.qmd
    - appendix-experimental/fase1-havanna.qmd
    - appendix-experimental/fase2-rbk.qmd
    - appendix-economico/costsRBKRAA.qmd
    - appendix-economico/simulations.qmd
    - appendix-economico/inversion.qmd
    - appendix-clinico.qmd
    - appendix-modelo.qmd

website:
  sidebar:
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "FastPGT"

      - href: appendix-technical.qmd
        text: "Apéndice Técnico"

      - section: "Apéndice Experimental"
        contents:
          - href: appendix-experimental/fase1-havanna.qmd
            text: "Fase 1 – Havanna"
          - href: appendix-experimental/fase2-rbk.qmd
            text: "Fase 2 – RBK"

      - section: "Apéndice Económico"
        contents:
          - href: appendix-economico/costsRBKRAA.qmd
            text: "Modelo de Costos"
          - href: appendix-economico/simulations.qmd
            text: "Simulaciones"
          - href: appendix-economico/inversion.qmd
            text: "Inversión"

      - href: appendix-clinico.qmd
        text: "Apéndice Clínico-Embriológico"

      - href: appendix-modelo.qmd
        text: "Apéndice Modelo"

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: styles.css